#
# SAML configuration for authentication via cul_omniauth.
#
development:
  provider: developer
  fields:
    - :uid
  uid_field: :uid

test:
  host: cas.columbia.edu
  login_url: /cas/login
  logout_url: /cas/logout
  service_validate_url: /cas/serviceValidate
  disable_ssl_verification: true
  provider: cas
  provider: saml
  service_validate_url: /cas/samlValidate

amesa_dev:
  host: cas.columbia.edu
  login_url: /cas/login
  logout_url: /cas/logout
  service_validate_url: /cas/serviceValidate
  disable_ssl_verification: true
  provider: cas
  provider: saml
  service_validate_url: /cas/samlValidate
amesa_test:
  host: cas.columbia.edu
  login_url: /cas/login
  logout_url: /cas/logout
  service_validate_url: /cas/serviceValidate
  disable_ssl_verification: true
  provider: cas
  provider: saml
  service_validate_url: /cas/samlValidate
amesa_prod:
  host: cas.columbia.edu
  login_url: /cas/login
  logout_url: /cas/logout
  service_validate_url: /cas/serviceValidate
  disable_ssl_verification: true
  provider: cas
  provider: saml
  service_validate_url: /cas/samlValidate
