development:
  new_scholar:
    - exampleuser@example.com
  scholar_edit:
    - exampleuser@example.com
test:
  new_scholar:
    - exampleuser@example.com
  scholar_edit:
    - exampleuser@example.com
